# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ajit Kumar
#tagline:          'A Jekyll theme'
description:      'Assistant Professor <br> Department of Mathematics <br> Shiv Nadar University'
url:              '/'
baseurl:          '/'
keywords:          'Ajit Kumar Shiv Nadar Openfoam numerical pde cfd fluid finite element assistant professor greater noida gomia'

author:
  name:           'Ajit Kumar'
  url:

include:
  - teaching
#paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/


# search engine optimization - AK - Aug 16 - 2017
gems:
  - jekyll-seo-tag
