# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ajit Kumar
#tagline:          'A Jekyll theme'
description:      'Assistant Professor <br> Department of Mathematics <br> Shiv Nadar University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ajit Kumar'
  url:

#paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/
