# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ajit Kumar
#tagline:          'A Jekyll theme'
description:      'Assistant Professor <br> Department of Mathematics <br> Shiv Nadar University'
url:              '/'
baseurl:          '/'
keywords:          'Ajit Kumar Shiv Nadar OpenFoam University India'

author:
  name:           'Ajit Kumar'
  url:

include:
  - teaching
#paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/


# search engine optimization - AK - Aug 16 - 2017
plugins:
  - jekyll-seo-tag
